web_s10186768/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using web_s10186768.DAL;
using web_s10186768.Models;


namespace web_s10186768.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public async Task<ActionResult> Index()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://ictonejourney.com");
            HttpResponseMessage response = await client.GetAsync("/api/books");
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                List<Book> bookList = JsonConvert.DeserializeObject<List<Book>>(data);
                return View(bookList);
            }
            else
            {
                return View(new List<Book>());
            }
        }





            // GET: Book/Details/5
            public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Book/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Book/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Book/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Book/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

web_s10186768/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/Site.css" rel="stylesheet" />
    <title>@ViewData["Title"] - NP Book Rental</title>
    <!-- Reference to Bootstrap CSS, JavaScript/JQuery files -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <!-- Reference to customized styling for this website -->
    <link rel="stylesheet" type="text/css" href="~/css/Site.css">
</head>
<body>
    <!-- Bootstrap container, centralise the container between margins -->
    <div class="container">
        <!-- 1st row -->
        <div class="row">
            <div class="col-sm-12">
                @if (Context.Session.GetString("Role") != null)
                {
                    if (Context.Session.GetString("Role") == "Staff")
                    {
                        @await Html.PartialAsync("_StaffMenu.cshtml")
                    }
                    if (Context.Session.GetString("Role") == "Student")
                    {
                        @await Html.PartialAsync("_StudentMenu.cshtml")
                    }

                }
            </div>
        </div>
        <!-- 2nd row -->
        <div class="row">
            <div class="col-sm-12">
                <p style="padding:2px 15px;">
                    @{
                        string userId = "Anonymous";
                        string userRole = "Unknown";
                        if (Context.Session.GetString("Role") != null)
                        {
                            userRole = Context.Session.GetString("Role");
                        }
                        if (Context.Session.GetString("LoginID") != null)
                        {
                            userId = Context.Session.GetString("LoginID");
                        }
                    }

                    Welcome,&nbsp;
                    <span style="font-weight:bold">@userId</span>&nbsp;
                    (Role: @userRole).&nbsp;

                </p>
            </div>
        </div>
        <!-- 3rd row -->
        <div class="row">
            <div class="col-sm-12">
                @RenderBody()
            </div>
        </div>
        <!-- 4th row -->
        <div class="row">
            <div class="col-sm-12" style="text-align: right">
                <hr />
                <footer>
                    <p style="padding-right:10px;">
                        WEB Practical Exercises - &copy;@DateTime.Today.Year
                        School of ICT, Ngee Ann Polytechnic
                    </p>
                </footer>
            </div>
        </div>
    </div>
</body>
</html>

web_s10186768/Views/Shared/_StaffMenu.cshtml
<!-- A grey navbar that expands horizontally at medium device -->
<nav class="navbar navbar-expand-md bg-light navbar-light">
    <!-- The brand(or icon) of the navbar -->
    <a class="navbar-brand" href="~/Home/StaffMain"
       style="font-size:32px; font-weight:bold; color:#3399FF;">
        NP Book Rental
    </a>
    <!-- Toggle/collapsible Button, also known as hamburger button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#staffNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Links in the navbar, displayed as drop-down list when collapsed -->
    <div class="collapse navbar-collapse" id="staffNavbar">
        <!-- Links that are aligned to the left,
        mr-auto: right margin auto-adjusted -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="~/Rental/Calculate">
                    Rental Calculator
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/Fine/Calculate">Fine Calculator</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/Staff/Index">View Staff</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/Branch/Index">View Branch</a>
            </li>
        </ul>
        <!-- Links that are aligned to the right,
        ml-auto: left margin auto-adjusted -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <!-- A link for logging out user -->
                <a class="nav-link" href="~/Home/LogOut">Log Out</a>
            </li>
        </ul>
    </div>
</nav>

web_s10186768/Views/Shared/_StudentMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<!-- A grey navbar that expands horizontally at medium device -->
<nav class="navbar navbar-expand-md bg-light navbar-light">
    <!-- The brand(or icon) of the navbar -->
    <a class="navbar-brand" href="~/Book/Index"
       style="font-size:32px; font-weight:bold; color:#3399FF;">
        NP Book Rental
    </a>
    <!-- Toggle/collapsible Button, also known as hamburger button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#studentNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Links in the navbar, displayed as drop-down list when collapsed -->
    <div class="collapse navbar-collapse" id="studentNavbar">
        <!-- Links that are aligned to the left,
        mr-auto: right margin auto-adjusted -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link"
                   asp-controller="Book"
                   asp-action="Index">View Books</a>
            </li>
        </ul>
        <!-- Links that are aligned to the right,
        ml-auto: left margin auto-adjusted -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <!-- A link for logging out user -->
                <a class="nav-link" href="~/Home/LogOut">Log Out</a>
            </li>
        </ul>
    </div>
</nav>